@logivity_api_HostAddress = http://localhost:5235

GET {{logivity_api_HostAddress}}/api/Shipments
Accept: application/json

###

GET {{logivity_api_HostAddress}}/api/Shipments?status=Open
Accept: application/json

###

POST {{logivity_api_HostAddress}}/api/Shipments
Content-Type: application/json

{
  "origin": "Rotterdam, NL",
  "destination": "Gothenburg, SE",
  "pickupDate": "2026-10-15",
  "description": "12 pallets of packaged electronics, 4.8 t"
}

###

POST {{logivity_api_HostAddress}}/api/shipments/1/bids
Content-Type: application/json

{
  "carrierName": "Nordic Freight AB",
  "price": 12500,
  "note": "Can pick up a day early"
}

###

GET {{logivity_api_HostAddress}}/api/shipments/1/bids
Accept: application/json

###

GET {{logivity_api_HostAddress}}/api/shipments/1/bids/1
Accept: application/json

###
